# Generated by Django 5.1.5 on 2025-02-04 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('session_type', models.CharField(choices=[('2-station', '2 Station'), ('4-station', '4 Station')], max_length=10)),
                ('payment_status', models.BooleanField(default=False)),
            ],
        ),
    ]
