# Generated by Django 5.1.5 on 2025-02-04 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_id',
            field=models.CharField(default='dfasd', max_length=255),
            preserve_default=False,
        ),
    ]
