# Generated by Django 5.1.5 on 2025-05-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolecture',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='video_lectures/thumbnails/'),
        ),
    ]
