# Generated by Django 5.1.5 on 2025-06-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_lectures', '0002_videolecture_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolecture',
            name='video',
            field=models.CharField(help_text='YouTube video URL', max_length=255),
        ),
    ]
